In [1]:
print("ok")

ok

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("../data/shipment_data.csv")

In [4]:
data.head()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,Yes,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,No,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,No,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,No,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,Yes,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

In [5]:
data.tail()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
6495,fffe3800370037003300,Jeffrey Freudenthal,0.37,37.0,10.0,16551.0,Brass,28.28,38.46,Yes,Yes,No,Airways,No,Wealthy,Yes,03/28/18,03/25/18,"New Robert, VT 85335",872.43
6496,fffe310036003400,Larry Edwards,0.67,15.0,NaN,18981.0,NaN,67.18,27.72,No,No,No,Roadways,No,Working Class,No,08/29/15,08/27/15,"New Joshua, VA 35766",1347.02
6497,fffe3600300031003300,Denise Worth,0.68,19.0,8.0,587.0,Clay,6.92,10.38,Yes,No,No,NaN,Yes,Wealthy,No,04/10/19,04/09/19,"Lake Kelly, MA 80823",354.55
6498,fffe3600350035003900,Daniel Drew,0.02,33.0,9.0,1269377.0,Stone,2929.13,69.76,No,Yes,No,Roadways,No,Working Class,Yes,03/10/19,03/12/19,"Hintonberg, UT 35006",5037.50
6499,fffe3700310031003600,Vernon Carroll,0.18,30.0,13.0,34729.0,Brass,46.63,78.25,No,Yes,No,Airways,No,Working Class,No,12/03/16,12/05/16,"New Christopher, AK 87406",722.47

In [6]:
data.shape

(6500, 20)

In [7]:
data.columns

Index(['Customer Id', 'Artist Name', 'Artist Reputation', 'Height', 'Width',
       'Weight', 'Material', 'Price Of Sculpture', 'Base Shipping Price',
       'International', 'Express Shipment', 'Installation Included',
       'Transport', 'Fragile', 'Customer Information', 'Remote Location',
       'Scheduled Date', 'Delivery Date', 'Customer Location', 'Cost'],
      dtype='object')

In [8]:
# data.rpow

In [9]:
# data.describe

In [10]:
type(data)

pandas.core.frame.DataFrame

In [11]:
data_dict=data.to_dict(orient='records')

In [12]:
# data_dict

In [13]:
len(data)

6500

In [14]:
len(data_dict)

6500

In [15]:
import os
from dotenv import load_dotenv

load_dotenv(dotenv_path="../.env")

True

In [16]:
DB_NAME=os.getenv("DB_NAME")
COLLECTION_NAME=os.getenv("COLLECTION_NAME")
CONNECTION_URL=os.getenv("CONNECTION_URI")

In [30]:
#print(DB_NAME)
#print(COLLECTION_NAME)
#pint(CONNECTION_URL)

In [18]:
import pymongo

client=pymongo.MongoClient(CONNECTION_URL)
data_base=client[DB_NAME]
collection=data_base[COLLECTION_NAME]

# Storing Data

In [19]:

rec = collection.insert_many(data_dict)

# Fetch data

In [20]:
records=collection.find()

In [21]:
records

In [22]:
records=collection.find().limit(5)

In [23]:
for i in records:
    print(i)

{'_id': ObjectId('6a0808bbf34c7e2f86d9cc37'), 'Customer Id': 'fffe3900350033003300', 'Artist Name': 'Billy Jenkins', 'Artist Reputation': 0.26, 'Height': 17.0, 'Width': 6.0, 'Weight': 4128.0, 'Material': 'Brass', 'Price Of Sculpture': 13.91, 'Base Shipping Price': 16.27, 'International': 'Yes', 'Express Shipment': 'Yes', 'Installation Included': 'No', 'Transport': 'Airways', 'Fragile': 'No', 'Customer Information': 'Working Class', 'Remote Location': 'No', 'Scheduled Date': '06/07/15', 'Delivery Date': '06/03/15', 'Customer Location': 'New Michelle, OH 50777', 'Cost': -283.29}
{'_id': ObjectId('6a0808bbf34c7e2f86d9cc38'), 'Customer Id': 'fffe3800330031003900', 'Artist Name': 'Jean Bryant', 'Artist Reputation': 0.28, 'Height': 3.0, 'Width': 3.0, 'Weight': 61.0, 'Material': 'Brass', 'Price Of Sculpture': 6.83, 'Base Shipping Price': 15.0, 'International': 'No', 'Express Shipment': 'No', 'Installation Included': 'No', 'Transport': 'Roadways', 'Fragile': 'No', 'Customer Information': 'Working Class', 'Remote Location': 'No', 'Scheduled Date': '03/06/17', 'Delivery Date': '03/05/17', 'Customer Location': 'New Michaelport, WY 12072', 'Cost': -159.96}
{'_id': ObjectId('6a0808bbf34c7e2f86d9cc39'), 'Customer Id': 'fffe3600370035003100', 'Artist Name': 'Laura Miller', 'Artist Reputation': 0.07, 'Height': 8.0, 'Width': 5.0, 'Weight': 237.0, 'Material': 'Clay', 'Price Of Sculpture': 4.96, 'Base Shipping Price': 21.18, 'International': 'No', 'Express Shipment': 'No', 'Installation Included': 'No', 'Transport': 'Roadways', 'Fragile': 'Yes', 'Customer Information': 'Working Class', 'Remote Location': 'Yes', 'Scheduled Date': '03/09/15', 'Delivery Date': '03/08/15', 'Customer Location': 'Bowmanshire, WA 19241', 'Cost': -154.29}
{'_id': ObjectId('6a0808bbf34c7e2f86d9cc3a'), 'Customer Id': 'fffe350031003300', 'Artist Name': 'Robert Chaires', 'Artist Reputation': 0.12, 'Height': 9.0, 'Width': nan, 'Weight': nan, 'Material': 'Aluminium', 'Price Of Sculpture': 5.81, 'Base Shipping Price': 16.31, 'International': 'No', 'Express Shipment': 'No', 'Installation Included': 'No', 'Transport': nan, 'Fragile': 'No', 'Customer Information': 'Wealthy', 'Remote Location': 'Yes', 'Scheduled Date': '05/24/15', 'Delivery Date': '05/20/15', 'Customer Location': 'East Robyn, KY 86375', 'Cost': -161.16}
{'_id': ObjectId('6a0808bbf34c7e2f86d9cc3b'), 'Customer Id': 'fffe3900320038003400', 'Artist Name': 'Rosalyn Krol', 'Artist Reputation': 0.15, 'Height': 17.0, 'Width': 6.0, 'Weight': 324.0, 'Material': 'Aluminium', 'Price Of Sculpture': 3.18, 'Base Shipping Price': 11.94, 'International': 'Yes', 'Express Shipment': 'Yes', 'Installation Included': 'Yes', 'Transport': 'Airways', 'Fragile': 'No', 'Customer Information': 'Working Class', 'Remote Location': 'No', 'Scheduled Date': '12/18/16', 'Delivery Date': '12/14/16', 'Customer Location': 'Aprilside, PA 52793', 'Cost': -159.23}

In [24]:
df=pd.DataFrame(list(collection.find()))

In [25]:
df.head()

,_id,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,...,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,6a0808bbf34c7e2f86d9cc37,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,...,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,6a0808bbf34c7e2f86d9cc38,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,...,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,6a0808bbf34c7e2f86d9cc39,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,...,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,6a0808bbf34c7e2f86d9cc3a,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,...,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,6a0808bbf34c7e2f86d9cc3b,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,...,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

In [26]:
if "_id" in df.columns:
    df.drop(columns="_id", inplace=True)

In [27]:
df.head()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,Yes,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,No,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,No,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,No,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,Yes,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

In [31]:
df.to_csv("Storing_data_from_MongoDB.csv", index=False)